	modLoader="javafml" 
	loaderVersion="[36,)"
	license="MIT License"


[[mods]] 


	modId="sjkz1code" 
	version="${file.jarVersion}" 
	displayName="sjkz1codes" 
	#displayURL="https://www.curseforge.com/minecraft/mc-mods/mcbreaker"
	logoFile="logo.png" 
	credits="ToastKun"
	authors="SJKZ1" 
	description='''An special mod for ToastKun'''



[[dependencies.sjkz1code]] 

		modId="forge" 
		mandatory=true 
		versionRange="[36.0.1,)" 
		ordering="NONE"
		side="BOTH"
		
[[dependencies.sjkz1code]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.16.5]"
		ordering="NONE"
		side="BOTH"