	modLoader="javafml" 
	loaderVersion="[36,)"
	license="MIT License"


[[mods]] 


	modId="sjkz1code" 
	version="${file.jarVersion}" 
	displayName="SJKZ1Code" 
	logoFile="logo.png" 
	credits="SJKZ1"
	authors="SJKZ1" 
	description='''My mod.'''



[[dependencies.sjkz1code]] 

		modId="forge" 
		mandatory=true 
		versionRange="[36.0.4,)" 
		ordering="NONE"
		side="BOTH"
		
[[dependencies.sjkz1code]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.16.5]"
		ordering="NONE"
		side="BOTH"
		
[[dependencies.sjkz1code]]
    modId="stevekungs_lib"
    mandatory=true
    versionRange="[4.0.3,)"
    ordering="NONE"
    side="CLIENT"
		